### ISSUE TITLE
RequestError: Error: getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by jackoliver** [recombee/node-api-client#5]
Hey, experiencing this using a Firebase Cloud Function
```
{ RequestError: Error: getaddrinfo ENOTFOUND rapi.recombee.com rapi.recombee.com:80
    at new RequestError (/user_code/node_modules/recombee-api-client/node_modules/request-promise/lib/errors.js:14:15)
    at Request.RP$callback [as _callback] (/user_code/node_modules/recombee-api-client/node_modules/request-promise/lib/rp.js:60:25)
    at self.callback (/user_code/node_modules/recombee-api-client/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/user_code/node_modules/recombee-api-client/node_modules/request/request.js:878:8)
    at emitOne (events.js:101:20)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at connectErrorNT (net.js:1025:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  name: 'RequestError',
  message: 'Error: getaddrinfo ENOTFOUND rapi.recombee.com rapi.recombee.com:80',
  cause: 
   { Error: getaddrinfo ENOTFOUND rapi.recombee.com rapi.recombee.com:80
       at errnoException (dns.js:28:10)
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
     code: 'ENOTFOUND',
     errno: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'rapi.recombee.com',
     host: 'rapi.recombee.com',
     port: 80 },
  error: 
   { Error: getaddrinfo ENOTFOUND rapi.recombee.com rapi.recombee.com:80
       at errnoException (dns.js:28:10)
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
     code: 'ENOTFOUND',
     errno: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'rapi.recombee.com',
     host: 'rapi.recombee.com',
     port: 80 },
  options: 
   { method: 'PUT',
     uri: 'http://rapi.recombee.com/serial/users/wmWpyWqCyQNbWpoQ8rJaXLKXEx02?hmac_timestamp=1521637516&hmac_sign=11428188a51ada875625288d5bbd5d2c5dacf91d',
     headers: 
      { Accept: 'application/json',
        'Content-Type': 'application/json',
        'User-Agent': 'recombee-node-api-client/2.0.0' },
     timeout: 1000,
     resolveWithFullResponse: true,
     json: true,
     body: {},
     callback: undefined,
     transform: undefined,
     simple: true },
  response: undefined }
```

Here's the markup concerned:
```
const { userId } = event.params
    const rqs = recombee.requests
    const client = new recombee.ApiClient('DB--ID--REDACTED--HERE', '--SECRET--KEY--REDACTED--HERE')
    client.send(new rqs.AddUser(userId, { cascadeCreate: true }))
    .then((resp) => {
      console.log(resp)
    })
    .catch(err => console.log(err))
```

**Comment by OndraFiedler** [comment]
Hi Jack,
maybe this can be related? https://github.com/nodejs/node/issues/5436#issuecomment-373002246
